# -*- coding: utf-8 -*-
"""CLIP Pressure Compensator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7vQTeGThknLvJwMSmtg8lab2Fsq7H3v
"""

"""
================================================================================
CLIP RESIN FLOW & PRESSURE COMPENSATION ENGINE (v2.0)
================================================================================
TARGET SYSTEM: Continuous Liquid Interface Production (CLIP)
OBJECTIVE: Mitigate center-of-part overcuring caused by horizontal resin
           replenishment starvation in thin deadzones.

PHYSICS MODEL:
    This script approximates the Steady-State Reynolds Equation for Lubrication.
    It treats the print slice as a 2D hydraulic network:
    - Reservoir (Black Pixels): High permeability (K_high).
    - Part (White Pixels): Low permeability (K_low) + Mass Sink (Q).

    By solving the Poisson Equation [∇ · (K ∇P) = Q], we map the relative vacuum
    required to pull resin to any specific coordinate.

AI AGENT DOCUMENTATION:
    1. SINK TERM (Q): Represents resin consumption. High density areas pull more
       resin from the periphery, creating a "Center of Mass" pressure drop.
    2. CONDUCTIVITY (K): Represents the gap height (h^3). Black channels allow
       lateral flow with minimal resistance.
    3. BOUNDARY CONDITIONS: Dirichlet (P=0) at image edges. This forces the
       model to assume all fresh resin comes from the outside reservoir,
       effectively underweighting replenishment from 'above' the plane.
================================================================================
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

class CLIPPressureSolver:
    def __init__(self, channel_conductivity=100.0, sink_strength=0.1):
        """
        Initialize the solver constants.

        :param channel_conductivity: Ratio of flow ease in open channels vs under parts.
                                     High values (100+) make the 'straws' very efficient.
        :param sink_strength: Scaling factor for vacuum generation. Higher values
                              sharpen the gradient between edge and center.
        """
        self.k_ratio = channel_conductivity
        self.q_strength = sink_strength

    def preprocess_image(self, path):
        """Loads and binarizes the input geometry."""
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise FileNotFoundError(f"Could not load image at {path}")

        # Normalize to 0.0-1.0 float
        mask = img.astype(np.float32) / 255.0
        # Ensure a strict binary mask for the logic
        mask = np.where(mask > 0.5, 1.0, 0.0).astype(np.float32)
        return mask

    def solve(self, mask, iterations=2000):
        """
        Iterative Jacobi solver for the Pressure Field.

        Why Jacobi? It's easily parallelizable and intuitively mimics
        the 'diffusion' of pressure through a porous medium.
        """
        rows, cols = mask.shape

        # K (Permeability Map): High in channels, 1.0 under the part.
        K = np.where(mask < 0.5, self.k_ratio, 1.0)

        # P (Pressure Field): Initialized to 0.
        P = np.zeros((rows, cols), dtype=np.float32)

        print(f"Starting solver: {iterations} iterations on {rows}x{cols} grid...")

        for i in range(iterations):
            # 5-point Stencil (Finite Difference)
            # We calculate the pressure based on the average of neighbors,
            # but we weight the neighbors by the Conductivity Map (K).

            P_up    = np.roll(P,  1, axis=0); P_up[0, :] = 0
            P_down  = np.roll(P, -1, axis=0); P_down[-1, :] = 0
            P_left  = np.roll(P,  1, axis=1); P_left[:, 0] = 0
            P_right = np.roll(P, -1, axis=1); P_right[:, -1] = 0

            # Compute weighted average (Simplified Diffusion)
            # In high-K areas (channels), pressure equalizes instantly.
            # In low-K areas (parts), pressure gradients persist.
            avg_P = (P_up + P_down + P_left + P_right) / 4.0

            # The 'Sink' Term: Every part pixel subtracts pressure (creates vacuum)
            # We use addition here for positive pressure value representation of vacuum
            P = avg_P + (mask * self.q_strength)

            # Enforce Reservoir Boundary: Edges are 'infinite' resin supply (P=0)
            P[0, :] = 0; P[-1, :] = 0; P[:, 0] = 0; P[:, -1] = 0

            # Optimization: Print progress every 20%
            if i % (iterations // 5) == 0:
                print(f"  Progress: {int(i/iterations*100)}%...")

        # Normalize 0 to 1 for use in grayscale mapping
        p_min, p_max = np.min(P), np.max(P)
        if p_max == 0: return P
        return (P - p_min) / (p_max - p_min)

    def generate_compensated_slice(self, mask, p_map, alpha=0.3):
        """
        Generates the final grayscale image for the printer.

        :param alpha: Compensation intensity (0.0 to 1.0).
                      At 0.3, the 'starved' center pixels will be dimmed by 30%.
        """
        # Linear attenuation based on calculated starvation (pressure)
        # Intensity = Max * (1 - (Relative_Vacuum * Alpha))
        correction = 1.0 - (p_map * alpha)

        # Mask the correction so it only applies to the 'Part' pixels
        final_grayscale = mask * correction

        # Convert back to 8-bit for printer hardware
        return (final_grayscale * 255).astype(np.uint8)

def run_demonstration(image_path):
    # 1. Initialize Solver
    # We set a high channel conductivity because 'Black' pixels are
    # hundreds of microns deep, while 'White' deadzones are ~50 microns.
    solver = CLIPPressureSolver(channel_conductivity=150.0, sink_strength=0.1)

    # 2. Process
    mask = solver.preprocess_image(image_path)
    pressure_field = solver.solve(mask, iterations=1500)

    # 3. Apply Compensation
    # Suggesting a 25% drop for the most starved interior zones
    final_img = solver.generate_compensated_slice(mask, pressure_field, alpha=0.25)

    # 4. Visualize Results
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    axes[0].imshow(mask, cmap='gray')
    axes[0].set_title("Input Geometry (The Straw)")

    # The pressure map shows where resin is 'struggling' to reach.
    im1 = axes[1].imshow(pressure_field, cmap='inferno')
    axes[1].set_title("Starvation Map (Relative Vacuum)")
    plt.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04)

    axes[2].imshow(final_img, cmap='gray', vmin=0, vmax=255)
    axes[2].set_title("Compensated Grayscale Slice")

    plt.tight_layout()
    plt.show()

    # Save the file
    output_name = "compensated_" + os.path.basename(image_path)
    cv2.imwrite(output_name, final_img)
    print(f"Saved compensated slice to: {output_name}")

if __name__ == "__main__":
    # To use: ensure '3.png' is in the same directory.
    try:
        run_demonstration('3.png')
    except Exception as e:
        print(f"Error: {e}")