# -*- coding: utf-8 -*-
"""SLA Image Processor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tijtxZkKkY8VDnCy80jR9QLZKmwLleVO
"""

import os
import glob
import re
import cv2
import numpy as np
import multiprocessing
from functools import partial

# ==============================================================================
# 1. USER CONFIGURATION (Update these paths before running)
# ==============================================================================
FOLDER_PATH = r'C:\Users\ehunt\OneDrive\Northwestern University Lab Work\Mirae\Wood K Pile\200umPores TwoScaffolds 24umLayers'
NEW_IMAGE_FILENAME = 'New.png'  # Make sure this is in the same directory as the script, or provide full path
OUTPUT_FOLDER = os.path.join(FOLDER_PATH, 'Processed_Output') # Or specify exactly what you want

# Hardcoded Image Constraints
MIN_INTENSITY = 100
MAX_INTENSITY = 255
ROWS = 1600
COLS = 2560

# ==============================================================================
# 2. HELPER FUNCTIONS
# ==============================================================================
def edge_enhance(original_image, blurring, filter_size, min_val, max_val):
    """
    Replicates MATLAB's Gaussian edge enhancement logic.
    """
    # OpenCV requires filter sizes to be odd integers
    if filter_size % 2 == 0:
        filter_size += 1

    # Apply Gaussian Blur. cv2.GaussianBlur uses kernel size and sigma (blurring)
    blurred_image = cv2.GaussianBlur(original_image, (filter_size, filter_size), blurring)

    # Isolate edges by subtracting the blur from the original
    edge_enhanced = original_image - blurred_image

    # Create a mask to ignore pure black background pixels
    mask = original_image > 0

    # Failsafe if the image is entirely empty
    if not np.any(mask):
        return original_image

    # Find min and max of ONLY the non-zero pixels
    min_i = np.min(edge_enhanced[mask])
    max_i = np.max(edge_enhanced[mask])

    # Normalize the image (prevent division by zero just in case)
    if max_i > min_i:
        normalized = (edge_enhanced - min_i) / (max_i - min_i)
    else:
        normalized = edge_enhanced - min_i

    # Scale to our desired intensity range
    scaled_image = normalized * (max_val - min_val) + min_val

    # Restore the black background exactly as it was
    scaled_image[~mask] = 0

    return scaled_image

def process_single_image(filename, edge_check, blurring, filter_size, global_check, gaussian_map, guide_padding):
    """
    This function processes a single image. It is separated out so that
    multiprocessing can send different images to different CPU cores simultaneously.
    """
    # Read image in grayscale format
    img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"Warning: Could not read {filename}")
        return None

    # Convert to float64 for math operations (equivalent to MATLAB's im2double logic here)
    # Note: MATLAB's im2double scales to 0-1, but the original script later clipped at 255.
    # To retain the 0-255 math logic, we just cast to float.
    img_float = img.astype(np.float64)
    intermediate = np.copy(img_float)

    # --- Edge Enhancement ---
    if edge_check == 1:
        intermediate = edge_enhance(intermediate, blurring, filter_size, MIN_INTENSITY, MAX_INTENSITY)

    # --- Global Blur Enhancement ---
    if global_check == 1:
        # Multiply by the global gaussian vignette map
        intermediate = intermediate * gaussian_map
        # Clip values to ensure they stay within valid 8-bit bounds
        intermediate = np.clip(intermediate, 0, 255)

    # --- Padding Normalization (Only if padding is ON, but other enhancements OFF) ---
    if guide_padding == 1 and edge_check == 0 and global_check == 0:
        mask = img_float > 0
        if np.any(mask):
            max_i = np.max(intermediate[mask])
            min_i = np.min(intermediate[mask])
            if max_i > min_i:
                intermediate = (intermediate - min_i) / (max_i - min_i)
            # Scale back to max/min intensity bounds
            intermediate = intermediate * (MAX_INTENSITY - MIN_INTENSITY) + MIN_INTENSITY
            # Keep background zero
            intermediate[~mask] = 0

    # Convert back to 8-bit unsigned integer for standard image saving
    final_img = np.clip(intermediate, 0, 255).astype(np.uint8)
    return final_img

# ==============================================================================
# 3. MAIN EXECUTION BLOCK
# ==============================================================================
# In Python, multiprocessing requires this if __name__ == '__main__' guard on Windows
if __name__ == '__main__':

    # --- CLI USER PROMPTS ---
    try:
        guide = int(input("\nNo Padding (0)\nPadding (1)\nChoice: ").strip() or "0")

        edge_enhancement_check = int(input("\nEdge Enhancement: No (0)\nYes (1)\nChoice: ").strip() or "1")
        blurring = 25
        if edge_enhancement_check == 1:
            blur_input = input("\nHow much should the Gaussian Blur be? (Default 25): ").strip()
            blurring = float(blur_input) if blur_input else 25.0

        global_enhancement_check = int(input("\nGlobal Enhancement: No (0)\nYes (1)\nChoice: ").strip() or "0")
        globe = 0.8
        sig = 6.0
        if global_enhancement_check == 1:
            globe_input = input("\nGlobal blurring ratio (0.5 = center is half intensity of edges. Default 0.8): ").strip()
            globe = float(globe_input) if globe_input else 0.8

            sig_input = input("\nGlobal Filter Size (~6 is default): ").strip()
            sig = float(sig_input) if sig_input else 6.0

    except ValueError:
        print("Invalid input detected. Defaulting to safe values (No Padding, Edge Enchancement ON, Global OFF).")
        guide, edge_enhancement_check, blurring, global_enhancement_check = 0, 1, 25.0, 0

    # --- GLOBAL GAUSSIAN MAP GENERATION ---
    gaussian_map = None
    if global_enhancement_check == 1:
        min_value = globe
        max_value = 1.0
        filter_size_global = max(ROWS, COLS)
        sigma = filter_size_global / sig

        # Create X and Y meshgrids
        x = np.arange(1, COLS + 1)
        y = np.arange(1, ROWS + 1)
        X, Y = np.meshgrid(x, y)

        center_x = COLS / 2.0
        center_y = ROWS / 2.0

        # Generate Gaussian Map
        gaussian_map = np.exp(-((X - center_x)**2 + (Y - center_y)**2) / (2 * sigma**2))
        gaussian_map = gaussian_map / np.max(gaussian_map)

        # Invert map (center lowest, edges highest) and scale
        gaussian_map = 1.0 - gaussian_map
        gaussian_map = min_value + (max_value - min_value) * gaussian_map

    # --- FILE INGESTION & SORTING ---
    # Read the padding template image
    new_image = cv2.imread(NEW_IMAGE_FILENAME, cv2.IMREAD_GRAYSCALE)
    if new_image is None and guide == 1:
        print(f"CRITICAL ERROR: Could not find padding image '{NEW_IMAGE_FILENAME}'. Exiting.")
        exit(1)

    # Get all .png files and naturally sort them (so 2.png comes before 10.png)
    search_path = os.path.join(FOLDER_PATH, '*.png')
    image_files = glob.glob(search_path)

    # Natural sort logic
    def extract_number(f):
        match = re.search(r'\d+', os.path.basename(f))
        return int(match.group()) if match else 0

    image_files.sort(key=extract_number)
    num_images = len(image_files)
    print(f"\nFound {num_images} images to process.")

    if num_images == 0:
        print("No images found. Check your folder path.")
        exit(1)

    # Calculate edge enhancement filter size beforehand
    edge_filter_size = int(2 * (2 * blurring) + 1)

    # --- PARALLEL IMAGE PROCESSING ---
    print("Processing images...")

    # Create a partial function to freeze the static arguments so we can map just the filenames
    worker_func = partial(
        process_single_image,
        edge_check=edge_enhancement_check,
        blurring=blurring,
        filter_size=edge_filter_size,
        global_check=global_enhancement_check,
        gaussian_map=gaussian_map,
        guide_padding=guide
    )

    # Execute the processing loop across available CPU cores (replicating MATLAB's parfor)
    with multiprocessing.Pool() as pool:
        # pool.map retains the sorted order of the input array automatically
        processed_images = pool.map(worker_func, image_files)

    # --- ARRAY ASSEMBLY & EXPORT ---
    print("Assembling and saving images...")
    if not os.path.exists(OUTPUT_FOLDER):
        os.makedirs(OUTPUT_FOLDER)

    final_output_list = []

    # Replicate MATLAB's cell array interleaving logic
    for img in processed_images:
        if img is not None:
            final_output_list.append(img)
            if guide == 1:
                final_output_list.append(new_image)

    # Save everything sequentially
    for i, out_img in enumerate(final_output_list):
        # Using 1-based indexing for filenames to match MATLAB script
        out_filename = os.path.join(OUTPUT_FOLDER, f"{i + 1}.png")
        cv2.imwrite(out_filename, out_img)

    print(f"Montage images saved successfully to: {OUTPUT_FOLDER}")